name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: choco install nim
      - run: .\gradlew.bat build --stacktrace
      - run: nimble install
      - run: nimble build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/